version: '3.8'

services:
  php-apache-environment:
    container_name: php-apache
    image: php:7.0.1-apache
    restart: always
    volumes:
      - /home/agetic/Data/php:/var/www/html/
    ports:
      - 80:80