# version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: "vault server -dev -dev-root-token-id=root"
    volumes:
      - vault-file:/vault/file
      - vault-logs:/vault/logs

volumes:
  vault-file:
  vault-logs:
