version: "3.7"

services:
  postgres:
    container_name: postgres
    image: 'postgres:12'
    restart: always
    volumes:
      - /home/javier/Data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
