version: "3.7"

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - /home/javier/Data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
