services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: javier
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql:
