version: '3.9'

services:
  postgres:
    image: postgres:13.5
    container_name: postgres_13_5
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - /home/javier/data/postgres13:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: javier@postgres.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 5050:80
    volumes:
      - /home/javier/data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres