# se cambio de puertos para tener otra version ejecutandoce
# Las carpeta pgadminp14 necesita permisos 777
version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - /home/javier/data/postgres14:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminp14
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: javier@postgres.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 5051:80
    volumes:
      - /home/javier/data/pgadminp14:/var/lib/pgadmin
    depends_on:
      - postgres