version: '3.8'

services:

  php-apache:
    container_name: php-apache
    build: .
    depends_on:
      - mysql
    restart: always
    volumes:
      - /home/agetic/Data/php/src:/var/www/html/
    ports:
      - 80:80

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - /home/agetic/Data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: mysql
    depends_on:
        - mysql