version: "3.9"

networks:
  myredisnet:

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - myredisnet

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redisinsight_data:/db
    depends_on:
      - redis
    networks:
      - myredisnet

volumes:
  redis_data:
  redisinsight_data: