networks:
  databasenet:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - databasenet

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - databasenet

volumes:
  postgres:
  pgadmin:
