networks:
  databasenet:


services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - databasenet
    # Agrega estos comandos para instalar las dependencias faltantes
    # command: sh -c "apk add --no-cache zstd-libs && docker-entrypoint.sh postgres"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - databasenet

volumes:
  postgres:
  pgadmin:
