version: '3.9'

services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
    - PGADMIN_DEFAULT_EMAIL=javier@postgres.com
    - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin: