services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      # CONFIGURACIÓN DE CONEXIÓN A MONGO (Crucial)
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: mongo # Usa el nombre del servicio de arriba como host
      # CREDENCIALES PARA ENTRAR A LA INTERFAZ WEB (http://localhost:8081)
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
    depends_on:
      - mongo
    networks:
      - mongo

volumes:
  mongo_data:

networks:
  mongo:
